trigger:
  - master
  - develop

jobs:
  - job: "macOS"
    pool:
      vmImage: "macOS-10.14"
    steps:
      - script: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
          pod install
          git submodule update --init
          wget https://github.com/divvun/pahkat/releases/download/0.6.0/pahkat-macos -O pahkat
          chmod +x pahkat
          git clone https://github.com/divvun/divvun-ci-config.git
          cd divvun-ci-config
          sh ./install-macos.sh
        displayName: "Install prerequisites"
        env:
          DIVVUN_KEY: $(divvunKey)
      - script: |
          set -e
          /bin/bash scripts/build.sh
        displayName: "Build"
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/MacDivvun.pkg"
          artifactName: macos
        displayName: "Publish artifact"
      - script: |
          set -e
          export PATH="$PATH:$(System.DefaultWorkingDirectory)"
          export DEPLOY_VERSION=`/usr/libexec/PlistBuddy Sources/Info.plist -c "Print :CFBundleShortVersionString"`
          sh divvun-ci-config/repo/scripts/pahkat_deploy_svn.sh https://pahkat.uit.no/repo/macos "$(System.DefaultWorkingDirectory)/MacDivvun.pkg" macdivvun $DEPLOY_VERSION
        displayName: "Deploy to nightly channel"
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          DEPLOY_SVN_USER: $(svnUser)
          DEPLOY_SVN_PASSWORD: $(svnPassword)
          DEPLOY_SVN_COMMIT: $(svnCommit)
