name: CI
on: [push, repository_dispatch]

jobs:
  build:
    runs-on: [self-hosted, macos-11, aarch64]
    defaults:
      run:
        shell: "/usr/bin/arch -arch arm64e /bin/bash {0}"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: macdivvun-service
    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: Get version
      id: version
      uses: divvun/actions/version@master
      with:
        xcode: macdivvun-service
        stable-channel: beta
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt
    - name: Install build tools from Pahkat for macOS
      uses: divvun/actions/pahkat/init@master
      with:
        repo: https://pahkat.uit.no/devtools/
        channel: nightly
        packages: pahkat-uploader, xcnotary
    - name: Build Divvun Manager
      run: |
        source $RUNNER_TEMP/divvun-ci-config/enc/env.sh
        cd macdivvun-service
        /bin/bash scripts/build.sh
    - name: Deploy to Pahkat
      uses: divvun/actions/deploy@master
      with:
        platform: macos
        package-id: macdivvun
        # repo: "https://pahkat.uit.no/divvun-installer/"
        # Temporary workaround
        repo: "https://pahkat.thetc.se/tools/"
        channel: ${{ steps.version.outputs.channel }}
        version: ${{ steps.version.outputs.version }}
        macos-pkg-id: "no.divvun.MacDivvun"
        payload-path: "${{ env.GITHUB_WORKSPACE }}macdivvun-service/MacDivvun.pkg"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
